services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-wallet-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - mini-wallet
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: mini-wallet-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mini-wallet
    depends_on:
      - app

  postgres:
    image: postgres:16-alpine
    container_name: mini-wallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mini_wallet
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini-wallet

  redis:
    image: redis:7-alpine
    container_name: mini-wallet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mini-wallet

networks:
  mini-wallet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
